#
# THIS IS AN EXAMPLE PROJECT MAKEFILE
#
ROOT=../../

LINKSCRIPT=$(ROOT)/gcc/linker.ld
ENTRYPT= # PUT ENTRY POINT HERE
SPCFLAGS= # PUT PROJECT-SPECIFIC CFLAGS HERE

#
# INCLUDE COMMON DEFINITIONS
#
include $(ROOT)/common.mk

#
# DEFINE RULES TO BUILD
#
$(PROJNAME).axf: # PUT BUILD FILES HERE


#
# ADD LIB OBJECT FILES NEEDED HERE
#
$(PROJNAME).axf: # PUT LIB FILES HERE

